### ISSUE TITLE
Footer design fungerer ikkje skikkeleg på mobil

### ISSUE THREAD

**Issue by Freheims** [odinho/nmu-netside#2]
![malungdom no_(Samsung Galaxy Note10+)](https://user-images.githubusercontent.com/11025842/78650800-b6d94380-78bf-11ea-9f6e-f79362714793.png)

Har observert problemet i Opera (57.1.2830.52480), Chrome (80.0.3987.162) og Samsung Internett (11.1.2.2) på Android 10 (Samsung Galaxy Note 9) og i Chrome (80.0.3987.149) på Windows 10.

**Comment by odinho** [comment]
Sjå der! ;)

Tek gjerne i mot PR ^_^
